import { type LanguagePreference } from "./preferences";

export function getCopy(language: LanguagePreference) {
  if (language === "EN") {
    return {
      navPocket: "My Pocket",
      navLobby: "Lobby",
      navDebt: "Ur Zeel",
      navSettings: "Settings",
      appearance: "Appearance",
      light: "Light",
      dark: "Dark",
      totalBalance: "Total balance",
      loadingAccounts: "Loading accounts...",
      noAccounts: "No accounts found.",
      createAccount: "Create account",
      close: "Close",
      new: "New",
      accountName: "Account name",
      add: "Add",
      creating: "Creating...",
      showLess: "Show Less",
      showMore: "Show More",
      income: "Income",
      expense: "Expense",
      transfer: "Transfer",
      account: "Account",
      toAccount: "To Account",
      selectAccount: "Select account",
      selectDestination: "Select destination",
      category: "Category",
      internalMovement: "Internal movement",
      price: "Amount",
      description: "Description",
      date: "Date",
      addTransaction: "Add Transaction",
      saving: "Saving...",
      monthSummaryLoading: "Loading monthly summary...",
      lastTransactions: "Last transactions",
      all: "All",
      loadingTransactions: "Loading transactions...",
      noTransactions: "No transactions in this filter.",
      settings: "Settings",
      profileDefaults: "Profile & defaults",
      user: "User",
      displayName: "Display name",
      email: "Email",
      login: "Login",
      reset: "Reset",
      save: "Save",
      preferences: "Preferences",
      language: "Language",
      mongolian: "Mongolian",
      english: "English",
      currency: "Currency",
      monthStart: "Month start",
      density: "Density",
      balanced: "Balanced",
      compact: "Compact",
      landing: "Landing",
      hideBalances: "Hide balances",
      enabled: "Enabled",
      disabled: "Disabled",
      monthChip: "Month",
    };
  }

  return {
    navPocket: "Миний хэтэвч",
    navLobby: "Лобби",
    navDebt: "Өр Зээл",
    navSettings: "Тохиргоо",
    appearance: "Харагдац",
    light: "Цайвар",
    dark: "Харанхуй",
    totalBalance: "Нийт үлдэгдэл",
    loadingAccounts: "Данс ачаалж байна...",
    noAccounts: "Данс олдсонгүй.",
    createAccount: "Данс нэмэх",
    close: "Хаах",
    new: "Шинэ",
    accountName: "Дансны нэр",
    add: "Нэмэх",
    creating: "Үүсгэж байна...",
    showLess: "Хураах",
    showMore: "Дэлгэрүүлэх",
    income: "Орлого",
    expense: "Зарлага",
    transfer: "Шилжүүлэг",
    account: "Данс",
    toAccount: "Очих данс",
    selectAccount: "Данс сонгох",
    selectDestination: "Очих данс сонгох",
    category: "Ангилал",
    internalMovement: "Дотоод шилжүүлэг",
    price: "Дүн",
    description: "Тайлбар",
    date: "Огноо",
    addTransaction: "Гүйлгээ нэмэх",
    saving: "Хадгалж байна...",
    monthSummaryLoading: "Сарын мэдээлэл ачаалж байна...",
    lastTransactions: "Сүүлийн гүйлгээнүүд",
    all: "Бүгд",
    loadingTransactions: "Гүйлгээнүүд ачаалж байна...",
    noTransactions: "Энэ шүүлтэд гүйлгээ алга.",
    settings: "Тохиргоо",
    profileDefaults: "Профайл ба үндсэн тохиргоо",
    user: "Хэрэглэгч",
    displayName: "Харагдах нэр",
    email: "Имэйл",
    login: "Нэвтрэлт",
    reset: "Сэргээх",
    save: "Хадгалах",
    preferences: "Сонголтууд",
    language: "Хэл",
    mongolian: "Монгол",
    english: "Англи",
    currency: "Валют",
    monthStart: "Сарын эхлэх өдөр",
    density: "Нягтрал",
    balanced: "Энгийн",
    compact: "Шахуу",
    landing: "Эхлэх хуудас",
    hideBalances: "Дүн нууцлах",
    enabled: "Идэвхтэй",
    disabled: "Идэвхгүй",
    monthChip: "Сар",
  };
}
